[package]
name = "pan-kelner"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.69"
colorgrad = "0.6.2"
image = "0.24.5"
reqwest = "0.11.14"
tera = "1.18.0"
thirtyfour = "0.31.0"
tokio = { version = "1.26.0", features = ["rt", "macros"] }
