name: Create a new page
on: [workflow_dispatch, push]

jobs:
  run-generate-the-page:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: rustup toolchain install stable --profile minimal
        - uses: Swatinem/rust-cache@v2
        - run: cargo build